### ISSUE TITLE
Error in displaying an override

### ISSUE THREAD

**Issue by niclas72** [jonfawcett/LoopFollow#50] opened 2020-06-24 19:50 UTC
When entering an override which is over 100% it is displayed as 0.0% at the Override line in the "info box" up to the right on the app screen.

**Comment by jonfawcett** [comment] 2020-06-24 20:54
I cannot reproduce this and it appears to be functioning correctly for me. Please send a screenshot the next time it happens. Closing this for now.

**Closed by jonfawcett** 2020-06-24 20:54 UTC
