### ISSUE TITLE
App crashes when using Nightscout Access tokens

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#45] opened 2020-06-23 20:11 UTC
I tested dev/mmol with Heroku config vars AUTH_DEFAULT_ROLES = admin, and Loop app seemed to work as it should (just tested very briefely). I seem to have problems as soon as I change AUTH_DEFAULT_ROLES back to "denied", and enter a token (which was given the role of "admin" in Nightscout).

Loop Follow app crashes instantly after loading NS data, and the settings are unavailable until deleting the app from iPhone (or iPad), and installing again from XCode.

**Comment by bjornoleh** [comment] 2020-06-23 20:17
Xcode run

`2020-06-23 21:49:26.232958+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.233099+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236337+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236438+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236497+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236535+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236623+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236672+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236717+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:26.236879+0200 Loop Follow[507:67246] [Unknown process name] CGAffineTransformInvert: singular matrix.
2020-06-23 21:49:33.246393+0200 Loop Follow[507:67246] [Warning] Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a table view cell's content view. We're considering the collapse unintentional and using standard height instead. Cell: <_TtGC6Eureka13SegmentedCellSS_: 0x155d49490; baseClass = UITableViewCell; frame = (0 0; 320 44); text = 'Units'; autoresize = W; layer = <CALayer: 0x283c73960>>
2020-06-23 21:49:42.260478+0200 Loop Follow[507:67428] [general] Connection to daemon was invalidated
2020-06-23 21:49:43.227379+0200 Loop Follow[507:67246] [Snapshotting] Snapshotting a view (0x155d91260, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
2020-06-23 21:49:46.524385+0200 Loop Follow[507:67246] [Snapshotting] Snapshotting a view (0x15721e000, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
2020-06-23 21:49:50.477418+0200 Loop Follow[507:67246] [Snapshotting] Snapshotting a view (0x157235e30, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
2020-06-23 21:49:56.113244+0200 Loop Follow[507:67246] [Snapshotting] Snapshotting a view (0x157251350, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
21:49:56 main timer ended <NSThread: 0x28293d080>{number = 1, name = main}
Enter download device status
entered device status task.
Enter BG Web Call
enter download profile
enter download basals
enter download bolus
enter download carbs
enter download cage
enter download sage
Start View Timer
2020-06-23 21:49:56.238957+0200 Loop Follow[507:67427] Task <E77DFF09-B625-46DC-B8EA-DEFFE340CD2F>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832d8b70 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/devicestatus.json?count=1, NSErrorFailingURLKey=h/api/v1/devicestatus.json?count=1, NSLocalizedDescription=unsupported URL}
in device status loop.
2020-06-23 21:49:56.239421+0200 Loop Follow[507:67427] Task <CE9D7E1C-099F-421F-B890-A56FA51593AD>.<2> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832de430 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/entries/sgv.json?count=289, NSErrorFailingURLKey=h/api/v1/entries/sgv.json?count=289, NSLocalizedDescription=unsupported URL}
start bg url
2020-06-23 21:49:56.241070+0200 Loop Follow[507:67427] Task <A861103E-2EE4-4C00-BAFE-BC6CEBDA405D>.<3> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832de2e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/profile/current.json, NSErrorFailingURLKey=h/api/v1/profile/current.json, NSLocalizedDescription=unsupported URL}
2020-06-23 21:49:56.241980+0200 Loop Follow[507:67427] Task <3C5C0E67-953D-4178-999A-26B1F8663B5B>.<4> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832de4c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/treatments.json?find%5BeventType%5D%5B$eq%5D=Temp%20Basal&find%5Bcreated_at%5D%5B$gte%5D=2020-06-22T19:49:56, NSErrorFailingURLKey=h/api/v1/treatments.json?find[eventType][$eq]=Temp%20Basal&find[created_at][$gte]=2020-06-22T19:49:56, NSLocalizedDescription=unsupported URL}
2020-06-23 21:49:56.242284+0200 Loop Follow[507:67428] Task <71129105-EBE8-461F-A6AF-98020C1B03BC>.<5> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832de550 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/treatments.json?find%5BeventType%5D=Correction%20Bolus&find%5Bcreated_at%5D%5B$gte%5D=2020-06-22T19:49:56, NSErrorFailingURLKey=h/api/v1/treatments.json?find[eventType]=Correction%20Bolus&find[created_at][$gte]=2020-06-22T19:49:56, NSLocalizedDescription=unsupported URL}
2020-06-23 21:49:56.243167+0200 Loop Follow[507:67428] Task <DB5C9958-5284-46FC-8794-A654E0B51AB2>.<6> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832de460 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/treatments.json?find%5BeventType%5D=Meal%20Bolus&find%5Bcreated_at%5D%5B$gte%5D=2020-06-22T19:49:56, NSErrorFailingURLKey=h/api/v1/treatments.json?find[eventType]=Meal%20Bolus&find[created_at][$gte]=2020-06-22T19:49:56, NSLocalizedDescription=unsupported URL}
2020-06-23 21:49:56.243378+0200 Loop Follow[507:67428] Task <5C1BEE05-7330-4D51-A486-DED7939C3C55>.<7> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832db780 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/treatments.json?find%5BeventType%5D=Site%20Change&count=1, NSErrorFailingURLKey=h/api/v1/treatments.json?find[eventType]=Site%20Change&count=1, NSLocalizedDescription=unsupported URL}
start cage url
2020-06-23 21:49:56.244202+0200 Loop Follow[507:67428] Task <1E020717-75BD-4BC1-A69D-FD63D0F8B76E>.<8> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x2832db960 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=h/api/v1/treatments.json?find%5BeventType%5D=Sensor%20Start&find%5Bcreated_at%5D%5B$gte%5D=2020-05-31&count=1, NSErrorFailingURLKey=h/api/v1/treatments.json?find[eventType]=Sensor%20Start&find[created_at][$gte]=2020-05-31&count=1, NSLocalizedDescription=unsupported URL}
start cage url
21:50:11view timer ended
21:50:26 main timer ended <NSThread: 0x28293d080>{number = 1, name = main}
Enter download device status
entered device status task.
Enter BG Web Call
enter download profile
enter download basals
enter download bolus
enter download carbs
enter download cage
enter download sage
Start View Timer
2020-06-23 21:50:26.316674+0200 Loop Follow[507:67569] Connection 1: received failure notification
2020-06-23 21:50:26.316837+0200 Loop Follow[507:67569] Connection 1: failed to connect 12:8, reason -1
2020-06-23 21:50:26.316924+0200 Loop Follow[507:67569] Connection 1: encountered error(12:8)
2020-06-23 21:50:26.321539+0200 Loop Follow[507:67532] Task <FA27F63A-9F46-484A-B8D5-7011335F11A0>.<9> HTTP load failed, 0/0 bytes (error code: -1003 [12:8])
2020-06-23 21:50:26.326766+0200 Loop Follow[507:67532] Task <FA27F63A-9F46-484A-B8D5-7011335F11A0>.<9> finished with error [-1003] Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x2832d6af0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://XXXXXXX.herokuapp.c/api/v1/devicestatus.json?count=1, NSErrorFailingURLKey=https://XXXXXXX.herokuapp.c/api/v1/devicestatus.json?count=1, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.}
in device status loop.
2020-06-23 21:50:26.328919+0200 Loop Follow[507:67532] Connection 2: received failure notification
2020-06-23 21:50:26.329015+0200 Loop Follow[507:67532] Connection 2: failed to connect 12:8, reason -1
2020-06-23 21:50:26.329070+0200 Loop Follow[507:67532] Connection 2: encountered error(12:8)
2020-06-23 21:50:26.331655+0200 Loop Follow[507:67570] Task <342F516C-214F-45EA-A949-D3C0329FFD29>.<10> HTTP load failed, 0/0 bytes (error code: -1003 [12:8])
2020-06-23 21:50:26.335006+0200 Loop Follow[507:67569] Task <342F516C-214F-45EA-A949-D3C0329FFD29>.<10> finished with error [-1003] Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x2832d6250 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://XXXXXX.herokuapp.c/api/v1/entries/sgv.json?count=289, NSErrorFailingURLKey=https://XXXXXXXX.herokuapp.c/api/v1/entries/sgv.json?count=289, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.}`

**Comment by bjornoleh** [comment] 2020-06-24 20:37
Some XCode screenshots from build in sync with dev-mmol today, still problems. NS site with mmol units and AUTH_DEFAULT_ROLES = denied

Loop Follow crashed immediately after inserting url / token, and/or selecting mmol units. Freeze in settings, exit when stopping the app in XCose. Upon restart of app from iPhone, the app terminates nearly instantly, but the BG value is displayed in the app badge, and in a split second some data was visible in the main screen.

![image](https://user-images.githubusercontent.com/63544115/85624852-d2581d00-b66a-11ea-8c1a-545199c92043.png)

**Comment by jonfawcett** [comment] 2020-06-24 20:40
I was just about to ask for these. The first errors show it's an invalid url and there is no token entered. Please put a break at line 273 of nightscout.swift... this should be just after the below code. Then I need to know what the left side of the debugger shows for urlStringDeviceStatus and token. you can dm them to me if you don't want to post here

var urlStringDeviceStatus = urlUser + "/api/v1/devicestatus.json?count=1"
        if token != "" {
            urlStringDeviceStatus = urlUser + "/api/v1/devicestatus.json?token=" + token + "&count=1"
        }

**Comment by jonfawcett** [comment] 2020-06-24 21:03
Fixed in commit https://github.com/jonfawcett/LoopFollow/tree/371b9de227a1005d26ebe9cd779e68ef4f53fd24

**Closed** 2020-06-24 21:21 UTC
Labels: bug

**Comment by PieterGit** [comment] 2022-06-19 16:04
The excessive use of ` CGAffineTransformInvert: singular matrix` in the Console log is caused by the underlying Charts 3.5.0 pod. See issue #168 for details. Adding a Nightscout with token-based authentication works as expected with current Loop (dev).
