### ISSUE TITLE
Speculations about iOS 15 Health sharing 

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#137] opened 2021-08-12 19:10 UTC
As Jon mentioned elsewhere,  Apple is bringing the possibility to share health data with iOS 15 this fall. And that there might be possibilities for and additional source of CGM data for Loop Follow this way.

https://www.apple.com/newsroom/2021/06/apple-advances-personal-health-by-introducing-secure-sharing-and-new-insights/

It seems the ability of alerting followers based on various health data is part of the package. Do Apple intend to allow third party apps to utilise the health data for alarms etc? Or will this be limited to within the Health app itself? 

If third party apps can take part in this, there should also be some way to keep such apps from being shut down? Any chance the silent mp3 playback can be omitted? That would save a bit of battery usage for LF.

**Comment by jonfawcett** [comment] 2021-08-16 14:17
I just installed IOS 15 Beta for Loop Follow testing.  Apple's alerts are very limited right now and don't look like there will be BG alerts directly. But I am hopeful that we can hook into shared health data as an alternative to using Nightscout. This will solve quite a few issues that NS presents which are typically the cause of most crashes. I don't know that it will help with background app usage though. But if I need to do a huge re-write for Apple Health, I will try to incorporate that as an option. eg. toggle switch between standard background mode (which might be killed) and silent audio (that won't be killed).

To start testing before IOS 15 is generally available, I need someone using Loop and IOS 15 beta that is willing to share health data with me. So please send me a DM if you are interested.

**Comment by bjornoleh** [comment] 2021-08-16 14:49
Thanks, let's hope the health sharing can become useful. 

A background mode toggle might be a good idea for testing. Do we know how (or if) other apps like Dexcom Follow and Sugarmate prevents being killed by iOS? 

On a tangent regarding the silent playback, do you expect any differences in battery drain frome one or two instances of Loop Follow? Are they adding up their usage, or sharing the same resources?

**Comment by jonfawcett** [comment] 2021-11-06 22:28
I’m going to close this as I’ve been able to finally test. Health sharing doesn’t share every detailed data entry. So this will not be useful at all at the moment

**Closed by jonfawcett** 2021-11-06 22:28 UTC
