### ISSUE TITLE
Current basal with AB branch not showing in "info box"

### ISSUE THREAD

**Issue by niclas72** [jonfawcett/LoopFollow#48] opened 2020-06-24 15:30 UTC
Current basal rates are often not displayed in the "info box" up to the right. It is however displayed in the graph. This is happening when using AB branch.

**Comment by jonfawcett** [comment] 2020-07-01 18:00
This should be fixed in dev branch. I'm not positive I have covered every scenario, so please let me know if you encounter any times when it isn't displayed after updating. FYI - the way I had to implement it to not cause a delay loading initial data means that if it is currently on scheduled basal, there is a 50/50 chance it may take 1 extra reading before starting to populate after first starting the app. This is because the basal profile is separate data from the temp basal database.

**Closed by jonfawcett** 2020-07-01 18:00 UTC

**Comment by naromero77** [comment] 2020-07-02 18:06
I am reporting what I see, just in case its not normal. At the moment, Loop has been zero-temping for about 30+ minutes. The INFO Box displays nothing, and then displays 0.0, then nothing, and then back to 0.0, etc. There is roughly a gap of at least 2 - 3 minutes, between displaying nothing and 0.0.

**Comment by jonfawcett** [comment] 2020-07-02 18:21
Please ensure you have built dev. You can confirm this if there is a debug setting to show the debug log

**Comment by naromero77** [comment] 2020-07-02 19:46
I am on dev now -- the Basal field still momentarily disappears, but I assume that this is because of a refresh. When a numerical value is displayed, i.e. not empty, it is the correct value.

**Comment by jonfawcett** [comment] 2020-07-02 20:49
Just pushed a fix to dev that should be the last of the crashes caused by the new scheduled basal display
